- name: haproxy setup
  hosts: all
  tasks:
  - name: ensure backend
    pfsensible.core.pfsense_haproxy_backend:
      name: labvm
      balance: uri
      httpcheck_method: GET
      state: present
  - name: remove old server
    pfsensible.core.pfsense_haproxy_backend_server:
      backend: labvm
      name: '{{ hostname }}'
      state: absent
  - name: add server
    pfsensible.core.pfsense_haproxy_backend_server:
      backend: labvm
      name: "{{ hostname }}"
      address: carr-lab2.home
      port: "{{ ttyd_port }}"
      state: present

