version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vmlab 
    restart: unless-stopped
    volumes:
      - ./app/:/app/app/:ro
      - ./data/:/app/data/
    ports:
      - "8007:5000"

