version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: vmlab 
    restart: unless-stopped
    volumes:
      - ./app/:/app/app/:ro
      - ./data/:/app/data/
      - ./tf/:/app/tf/
    ports:
      - "8007:5000"
    links:
      - "db"
    environment:
      - DATABASE_URL=mysql+pymysql://vmlab:SecREt@db:3306/vmlab_db
      - ADMIN_PASS=admin
    depends_on:
      - db
  db:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SEcreT
      - MYSQL_PASSWORD=SecREt
      - MYSQL_USER=vmlab
      - MYSQL_DATABASE=vmlab_db
volumes:
  mysql:
