"""empty message

Revision ID: 1d17904a4579
Revises: 2c3ca1ada869
Create Date: 2022-05-06 03:42:00.459021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d17904a4579'
down_revision = '2c3ca1ada869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Course', type_='foreignkey')
    op.create_foreign_key(None, 'Course', 'VM', ['vm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Course', type_='foreignkey')
    op.create_foreign_key(None, 'Course', 'User', ['vm_id'], ['id'])
    # ### end Alembic commands ###
