"""empty message

Revision ID: 51e224c2da2b
Revises: 
Create Date: 2022-05-06 04:15:07.346479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e224c2da2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_name'), 'Role', ['name'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('VM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_name', sa.String(length=32), nullable=True),
    sa.Column('vm_desc', sa.String(length=120), nullable=True),
    sa.Column('path', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VM_path'), 'VM', ['path'], unique=False)
    op.create_index(op.f('ix_VM_vm_desc'), 'VM', ['vm_desc'], unique=False)
    op.create_index(op.f('ix_VM_vm_name'), 'VM', ['vm_name'], unique=True)
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=32), nullable=True),
    sa.Column('course_desc', sa.String(length=120), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['VM.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Course_course_desc'), 'Course', ['course_desc'], unique=True)
    op.create_index(op.f('ix_Course_course_name'), 'Course', ['course_name'], unique=True)
    op.create_table('user_role',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['Role.id'], ),
    sa.ForeignKeyConstraint(['user'], ['User.id'], )
    )
    op.create_table('Instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Instance_url'), 'Instance', ['url'], unique=True)
    op.create_table('assignment',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['user'], ['User.id'], )
    )
    op.create_table('user_instance',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('instance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance'], ['Instance.id'], ),
    sa.ForeignKeyConstraint(['user'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_instance')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_Instance_url'), table_name='Instance')
    op.drop_table('Instance')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_Course_course_name'), table_name='Course')
    op.drop_index(op.f('ix_Course_course_desc'), table_name='Course')
    op.drop_table('Course')
    op.drop_index(op.f('ix_VM_vm_name'), table_name='VM')
    op.drop_index(op.f('ix_VM_vm_desc'), table_name='VM')
    op.drop_index(op.f('ix_VM_path'), table_name='VM')
    op.drop_table('VM')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Role_name'), table_name='Role')
    op.drop_table('Role')
    # ### end Alembic commands ###
